import useStore from '@/helpers/store'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'



const Home: NextPage = () => {
  const { currentFlows } = useStore()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      lists of reddit bar


      <button>CREATE</button>
      {currentFlows.map((item, i) =>
        <Link
          key={i}
          href={`/flow/${item?.title}`}
        >{item?.title}</Link>
      )}

    </div>
  )
}

export default Home

// #414a4c	(65,74,76)
// #3b444b	(59,68,75)
// #353839	(53,56,57)
// #232b2b
