import Confirmation from "@/components/modals/Confirmation";
import useModal from "@/helpers/hooks/useModal";
import useStore from "@/helpers/store";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { WalletDisconnectButton, WalletMultiButton } from '@solana/wallet-adapter-react-ui';

const Home: NextPage = () => {

  // const { showModal, closeModal } = useModal()
  return (
    <div className="bg-gray-800 h-full w-full min-h-screen p-6">
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}



      <div className="text-8xl text-white font-semibold">Atomixy - The next wiki</div>
      <div className={styles.walletButtons}>
        <WalletMultiButton />
        <WalletDisconnectButton />
      </div>

      {/* IMAGES OF FLOW examples */}
      <br />
      <br />
      <br />
      <div className=" grid grid-cols-2 gap-2">
        <div className="bg-purple-300"></div>
        <div className=" max-h-96 overflow-scroll">
          {[1, 1, 1, 1, 1, 1].map((item, i) => <List key={i} />)}
        </div>
      </div>

    </div>
  );
};

export default Home;

// #414a4c	(65,74,76)
// #3b444b	(59,68,75)
// #353839	(53,56,57)
// #232b2b

const List = () => {

  return (
    <div className="p-4 mb-4 mx-1 bg-white rounded-md  ">
      <div className="text-gray-700 font-semibold ">Title Structs and Interfaces</div>
      <div className="text-gray-400 text-sm ">Description, Although it would be possible for us to write programs only using Go's built-in data types, at some point it would become quite tedious. Consider a program that interacts with shapes:</div>
      <div>Created by</div>
      <div>tags tags tags</div>
    </div>
  )
}