import Button from "@/components/Button";
import Layout from "@/components/Layout";
import useLoadList from "@/helpers/hooks/useLoadList";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import moment from "moment";
import {
  getNetworkName,
  getNetworkColorName,
  localAbi,
  localAddress,
} from "@/helpers/utils/networks";
import useDynamicContract from "@/helpers/hooks/useDynamicContract";
import { useWeb3React } from "@web3-react/core";
import { ethers } from "ethers";

// const { ethereum } = window

const Home: NextPage = () => {
  // const { showModal, closeModal } = useModal()
  const { active, error, activate, chainId, account, setError } =
    useWeb3React();
  const x = useDynamicContract(localAddress, localAbi, true);
  console.log(x, "x");
  return (
    <Layout>
      <div className="bgmain h-full w-full min-h-screen p-6">
        {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

        <button
          onClick={async () => {
            const parsedAmount = ethers.utils.parseEther("4");
            console.log(parsedAmount, "parsedamount");
            // 200.000.000.000.000.000.000
            // 6*3 = 18

            try {
              // await ethereum.request({
              //     method: 'eth_sendTransaction',
              //     params: [
              //       {
              //         from: connectedAccount,
              //         to: address,
              //         gas: '0x5208',
              //         value: parsedAmount._hex,
              //       },
              //     ],
              //   })

              const getx = await x?.getAddressTransactions(
                "0x70997970c51812dc3a010c7d01b50e0d17dc79c8"
              );
              console.log(getx, typeof getx);
              // const tx = await x?.sendMoney(

              //     "0x70997970c51812dc3a010c7d01b50e0d17dc79c8",
              //     parsedAmount,
              //     "abc"
              // )

              // console.log(`Loading - ${tx.hash}`)
              // await tx.wait()
              // console.log(`Success - ${tx.hash}`)

              // const transactionCount = await x?.getTransactionsCount()
              // console.log('transactionCount', transactionCount.toNumber())
            } catch (error) {
              console.log(error, "ERROR");
            }
          }}
        >
          send money?
        </button>
      </div>
    </Layout>
  );
};

export default Home;
